// <auto-generated />
using System;
using Dts.RegistroTiempos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dts.RegistroTiempos.Data.Migrations
{
    [DbContext(typeof(TiemposDbContext))]
    partial class TiemposDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dts.RegistroTiempos.Model.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<int>("EmpleadoId");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Actividad");
                });

            modelBuilder.Entity("Dts.RegistroTiempos.Model.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos");

                    b.Property<string>("Nombres");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("Dts.RegistroTiempos.Model.Tiempo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActividadId");

                    b.Property<DateTime>("Fecha");

                    b.Property<int>("Hora");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.ToTable("Tiempo");
                });

            modelBuilder.Entity("Dts.RegistroTiempos.Model.Actividad", b =>
                {
                    b.HasOne("Dts.RegistroTiempos.Model.Empleado")
                        .WithMany("Actividades")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dts.RegistroTiempos.Model.Tiempo", b =>
                {
                    b.HasOne("Dts.RegistroTiempos.Model.Actividad")
                        .WithMany("Tiempos")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
